#!/usr/bin/env python3
"""
cc-efficiency — Claude Code Efficiency Analyzer

Detects wasteful usage patterns in your Claude Code sessions,
estimates token overhead, and gives actionable recommendations.

Reads from ~/.claude/.dashboard-events.jsonl (generated by hooks).
Zero dependencies — Python 3.8+ stdlib only.

Usage:
    python cc_efficiency.py              # Last 7 days
    python cc_efficiency.py --days 30    # Last 30 days
    python cc_efficiency.py --all        # All time
    python cc_efficiency.py --json       # Machine-readable output
"""

import json
import sys
import argparse
from datetime import datetime, timedelta
from collections import defaultdict, Counter
from pathlib import Path

CLAUDE_DIR = Path.home() / ".claude"
EVENTS_FILE = CLAUDE_DIR / ".dashboard-events.jsonl"
HISTORY_FILE = CLAUDE_DIR / "history.jsonl"
EFFICIENCY_DB = CLAUDE_DIR / ".efficiency-events.jsonl"

# Token cost heuristics (conservative per-call estimates)
TOKEN_COSTS = {
    "bash_for_search": 400,
    "read_after_edit": 800,
    "search_churn_cycle": 1200,
    "toolsearch_call": 350,
    "agent_for_simple": 6000,
    "rapid_fire_edits": 200,
    "web_search_local": 1500,
}

# Context cost heuristics (tokens per item loaded into system prompt)
CONTEXT_COSTS = {
    "deferred_tool_listing": 15,     # one tool name line in system prompt
    "loaded_tool_schema": 200,       # full JSON schema when ToolSearch loads it
    "skill_listing": 30,             # one skill entry in system prompt
    "mcp_instructions": 150,         # average MCP server instruction block
}


def load_jsonl(path, since_ts=None):
    items = []
    if not path.exists():
        return items
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
                if since_ts and e.get("timestamp", 0) < since_ts:
                    continue
                items.append(e)
            except json.JSONDecodeError:
                continue
    return items


def group_by_session(events):
    sessions = defaultdict(list)
    for e in events:
        if e.get("type") == "PostToolUse":
            sessions[e.get("sessionId", "unknown")].append(e)
    for sid in sessions:
        sessions[sid].sort(key=lambda x: x.get("timestamp", 0))
    return dict(sessions)


# ── Detectors ─────────────────────────────────────────────

def detect_bash_overuse(sessions):
    """Bash calls that should be Grep/Read/Glob — high ratio = shell habit."""
    total_tools = bash_count = 0
    per_session = []
    for sid, events in sessions.items():
        s_total = len(events)
        s_bash = sum(1 for e in events if e.get("tool") == "Bash")
        total_tools += s_total
        bash_count += s_bash
        if s_total >= 10:
            per_session.append({"session": sid[:8], "bash_pct": round(s_bash / s_total * 100, 1),
                                "bash_count": s_bash, "total": s_total})

    ratio = bash_count / total_tools if total_tools else 0
    worst = sorted(per_session, key=lambda x: -x["bash_pct"])[:3]
    wasted = max(0, bash_count - int(total_tools * 0.15))
    return {
        "id": "bash_overuse", "name": "Bash Overuse",
        "severity": "high" if ratio > 0.25 else "medium" if ratio > 0.18 else "low",
        "bash_count": bash_count, "total_tools": total_tools,
        "ratio": round(ratio * 100, 1), "healthy_range": "10-15%",
        "worst_sessions": worst, "wasted_calls": wasted,
        "est_token_waste": wasted * TOKEN_COSTS["bash_for_search"],
        "recommendation": "Use Grep instead of grep/rg in Bash. Use Read instead of cat/head/tail. "
                          "Use Glob instead of find/ls. Dedicated tools return structured output "
                          "(fewer tokens) and skip shell overhead.",
    }


def detect_search_churn(sessions):
    """4+ consecutive Grep/Read/Glob calls — can't find what you need."""
    churn = []
    for sid, events in sessions.items():
        window = []
        for e in events:
            tool = e.get("tool", "")
            if tool in ("Grep", "Read", "Glob"):
                window.append({"tool": tool, "ts": e.get("timestamp", 0)})
            else:
                if len(window) >= 4:
                    sc = sum(1 for w in window if w["tool"] in ("Grep", "Glob"))
                    rc = sum(1 for w in window if w["tool"] == "Read")
                    if sc >= 2 and rc >= 2:
                        churn.append({"session": sid[:8], "length": len(window),
                                      "duration_s": round((window[-1]["ts"] - window[0]["ts"]) / 1000, 1)})
                window = []
        if len(window) >= 4:
            sc = sum(1 for w in window if w["tool"] in ("Grep", "Glob"))
            rc = sum(1 for w in window if w["tool"] == "Read")
            if sc >= 2 and rc >= 2:
                churn.append({"session": sid[:8], "length": len(window),
                              "duration_s": round((window[-1]["ts"] - window[0]["ts"]) / 1000, 1)})

    return {
        "id": "search_churn", "name": "Search Churn (Floundering)",
        "severity": "high" if len(churn) > 10 else "medium" if len(churn) > 3 else "low",
        "instances": len(churn), "total_churn_calls": sum(c["length"] for c in churn),
        "worst": sorted(churn, key=lambda x: -x["length"])[:5],
        "est_token_waste": len(churn) * TOKEN_COSTS["search_churn_cycle"],
        "recommendation": "When you can't find something in 2 searches, use the Explore agent "
                          "or ask Claude to search more broadly. Add glob filters to Grep. "
                          "Add key file paths to CLAUDE.md so Claude knows where to look.",
    }


def detect_toolsearch_overhead(events):
    """ToolSearch loads MCP schemas at runtime — pre-allow tools instead."""
    count = sum(1 for e in events if e.get("type") == "PostToolUse" and e.get("tool") == "ToolSearch")
    total = sum(1 for e in events if e.get("type") == "PostToolUse")
    return {
        "id": "toolsearch_overhead", "name": "ToolSearch Overhead",
        "severity": "high" if count > 100 else "medium" if count > 30 else "low",
        "count": count, "ratio_pct": round(count / total * 100, 1) if total else 0,
        "est_token_waste": count * TOKEN_COSTS["toolsearch_call"],
        "recommendation": "Add frequently-used MCP tools to permissions.allow in settings.json "
                          "so schemas load upfront. Example: 'mcp__duckdb__*' saves ~350 tokens "
                          "per avoided ToolSearch.",
    }


def detect_read_after_edit(sessions):
    """Read within 5s of Edit — unnecessary verification."""
    count = 0
    for sid, events in sessions.items():
        for i in range(1, len(events)):
            if (events[i - 1].get("tool") == "Edit" and events[i].get("tool") == "Read"
                    and events[i]["timestamp"] - events[i - 1]["timestamp"] < 5000):
                count += 1
    return {
        "id": "read_after_edit", "name": "Read-After-Edit Verification",
        "severity": "medium" if count > 20 else "low",
        "count": count, "est_token_waste": count * TOKEN_COSTS["read_after_edit"],
        "recommendation": "Edit confirms success -- no need to re-read. Add to CLAUDE.md: "
                          "'Do not re-read a file after editing to verify.'",
    }


def detect_rapid_fire_edits(sessions):
    """4+ Edit calls within 10s — should be batched into fewer calls."""
    bursts = []
    for sid, events in sessions.items():
        window = []
        for e in events:
            if e.get("tool") == "Edit":
                if window and e["timestamp"] - window[-1]["timestamp"] > 10000:
                    if len(window) >= 4:
                        bursts.append({"session": sid[:8], "count": len(window),
                                       "span_s": round((window[-1]["timestamp"] - window[0]["timestamp"]) / 1000, 1)})
                    window = []
                window.append(e)
            else:
                if len(window) >= 4:
                    bursts.append({"session": sid[:8], "count": len(window),
                                   "span_s": round((window[-1]["timestamp"] - window[0]["timestamp"]) / 1000, 1)})
                window = []
    extra = sum(max(0, b["count"] - 2) for b in bursts)
    return {
        "id": "rapid_fire_edits", "name": "Rapid-Fire Small Edits",
        "severity": "medium" if len(bursts) > 10 else "low",
        "burst_count": len(bursts), "extra_edits": extra,
        "worst": sorted(bursts, key=lambda x: -x["count"])[:5],
        "est_token_waste": extra * TOKEN_COSTS["rapid_fire_edits"],
        "recommendation": "Multiple tiny edits cost tokens per round-trip. Describe related "
                          "changes together so Claude batches them. Use Write for full rewrites "
                          "instead of many incremental edits.",
    }


def detect_agent_overuse(sessions):
    """Agent spawns for tasks solvable with 1-2 direct tool calls."""
    agent_count = total = 0
    for sid, events in sessions.items():
        for e in events:
            total += 1
            if e.get("tool") == "Agent":
                agent_count += 1
    ratio = agent_count / total if total else 0
    excess = max(0, agent_count - int(total * 0.05))
    return {
        "id": "agent_overuse", "name": "Agent Spawn Overhead",
        "severity": "high" if ratio > 0.08 else "medium" if ratio > 0.04 else "low",
        "agent_count": agent_count, "total_tools": total,
        "ratio_pct": round(ratio * 100, 1), "healthy_range": "1-3%",
        "excess": excess, "est_token_waste": excess * TOKEN_COSTS["agent_for_simple"],
        "recommendation": "Each Agent duplicates conversation context (~6K+ tokens). Use Grep/Read "
                          "directly for simple lookups. Reserve Agent for multi-step research or "
                          "parallel independent tasks.",
    }


def detect_websearch_for_local(sessions):
    """WebSearch followed by local search — answer was in the codebase."""
    total_ws = ws_then_local = 0
    for sid, events in sessions.items():
        for i, e in enumerate(events):
            if e.get("tool") == "WebSearch":
                total_ws += 1
                following = events[i + 1:i + 4]
                if sum(1 for f in following if f.get("tool") in ("Read", "Grep", "Glob")) >= 2:
                    ws_then_local += 1
    return {
        "id": "websearch_for_local", "name": "WebSearch for Local Answers",
        "severity": "medium" if ws_then_local > 5 else "low",
        "total_websearches": total_ws, "likely_local": ws_then_local,
        "est_token_waste": ws_then_local * TOKEN_COSTS["web_search_local"],
        "recommendation": "WebSearch results inject many tokens. Search locally first. Add "
                          "architecture notes to CLAUDE.md so Claude checks the codebase "
                          "before the web.",
    }


# ── Trends & Metrics ─────────────────────────────────────

def compute_weekly_trends(events):
    weeks = defaultdict(lambda: {"tool_count": 0, "bash": 0, "agent": 0, "ts": 0, "sessions": set()})
    for e in events:
        if e.get("type") != "PostToolUse":
            continue
        dt = datetime.fromtimestamp(e.get("timestamp", 0) / 1000)
        wk = dt.strftime("%Y-W%W")
        tool = e.get("tool", "")
        weeks[wk]["tool_count"] += 1
        weeks[wk]["sessions"].add(e.get("sessionId", ""))
        if tool == "Bash": weeks[wk]["bash"] += 1
        if tool == "Agent": weeks[wk]["agent"] += 1
        if tool == "ToolSearch": weeks[wk]["ts"] += 1

    trends = []
    for wk in sorted(weeks):
        w = weeks[wk]
        t = w["tool_count"]
        if t < 10:
            continue
        trends.append({"week": wk, "sessions": len(w["sessions"]), "tools": t,
                        "bash_pct": round(w["bash"] / t * 100, 1),
                        "agent_pct": round(w["agent"] / t * 100, 1),
                        "ts_pct": round(w["ts"] / t * 100, 1)})
    return trends


def compute_time_of_day(events):
    hours = Counter()
    for e in events:
        if e.get("type") == "PostToolUse":
            hours[datetime.fromtimestamp(e["timestamp"] / 1000).hour] += 1
    total = sum(hours.values()) or 1
    return [{"hour": h, "count": hours.get(h, 0), "pct": round(hours.get(h, 0) / total * 100, 1),
             "bar": "#" * int(hours.get(h, 0) / total * 100 * 2)} for h in range(24)]


def analyze_mcp_adoption(events):
    mcp = Counter()
    for e in events:
        if e.get("type") == "PostToolUse":
            tool = e.get("tool", "")
            if tool.startswith("mcp__"):
                mcp[tool.split("__")[1]] += 1
    return dict(mcp.most_common())


def analyze_enhanced(path, since_ts):
    items = load_jsonl(path, since_ts)
    errors = [e for e in items if e.get("event") == "PostToolUseFailure"]
    denials = [e for e in items if e.get("event") == "PermissionDenied"]
    return {
        "errors": {"total": len(errors), "by_tool": dict(Counter(e.get("tool", "?") for e in errors).most_common(5))},
        "denials": {"total": len(denials), "by_tool": dict(Counter(e.get("tool", "?") for e in denials).most_common(5))},
        "has_data": len(items) > 0,
    }


# ── Context Audit ────────────────────────────────────────

def _find_mcp_configs():
    """Find all .mcp.json files (global + project-level).

    Scans: ~/.claude/.mcp.json, CWD/.mcp.json, and any project dirs
    referenced in recent dashboard events (via session CWD tracking).
    """
    configs = {}
    # Global config
    global_mcp = CLAUDE_DIR / ".mcp.json"
    if global_mcp.exists():
        configs[str(global_mcp)] = ("global", global_mcp)
    # CWD config
    cwd_mcp = Path.cwd() / ".mcp.json"
    if cwd_mcp.exists():
        configs[str(cwd_mcp)] = ("project", cwd_mcp)
    # Scan known project dirs from Claude's project index
    projects_dir = CLAUDE_DIR / "projects"
    if projects_dir.exists():
        for proj in projects_dir.iterdir():
            if not proj.is_dir():
                continue
            # Project dir name encodes the path (c--Projects--foo -> c:/Projects/foo)
            # Try to reconstruct the original path
            name = proj.name
            # Common pattern: drive-letter--path--segments
            parts = name.split("-")
            if len(parts) >= 2 and len(parts[0]) == 1:
                # Looks like a path: c-Projects-foo -> c:/Projects/foo
                drive = parts[0]
                rest = "/".join(parts[1:])
                candidate = Path(f"{drive}:/{rest}") / ".mcp.json"
                if candidate.exists() and str(candidate) not in configs:
                    configs[str(candidate)] = ("project", candidate)
    return list(configs.values())


def _count_mcp_tools_from_events(events):
    """Count unique tool names per MCP server from actual usage."""
    server_tools = defaultdict(set)
    for e in events:
        if e.get("type") != "PostToolUse":
            continue
        tool = e.get("tool", "")
        if tool.startswith("mcp__"):
            parts = tool.split("__")
            if len(parts) >= 3:
                server_tools[parts[1]].add(tool)
    return {k: len(v) for k, v in server_tools.items()}


def _estimate_server_tools(server_name, tools_seen):
    """Estimate total tool count for a server based on observed tools.

    Servers expose many more tools than get used. We estimate the full
    count based on known server sizes. If unknown, use the observed count
    with a multiplier (most users only touch 10-30% of available tools).
    """
    # Known server sizes (approximate, based on common MCP servers)
    known = {
        "claude-flow": 185,
        "mobile": 70,
        "playwright": 30,
        "duckdb": 4,
        "yfinance": 20,
        "context7": 2,
        "sequential-thinking": 1,
        "filesystem": 8,
        "github": 25,
        "postgres": 5,
        "sqlite": 5,
        "memory": 6,
        "fetch": 2,
        "brave-search": 2,
        "puppeteer": 15,
        "slack": 10,
        "linear": 15,
        "sentry": 8,
        "supabase": 20,
    }
    if server_name in known:
        return known[server_name]
    # Unknown server: use observed tools * 3 (assume ~33% usage), min 5
    return max(5, tools_seen * 3)


def _count_skills():
    """Count installed skills by scanning the skills directory."""
    skills_dir = CLAUDE_DIR / "skills"
    count = 0
    if skills_dir.exists():
        for item in skills_dir.iterdir():
            if item.is_dir() and (item / "SKILL.md").exists():
                count += 1
    return count


def _count_plugins():
    """Count enabled plugins from settings.json."""
    settings_path = CLAUDE_DIR / "settings.json"
    if not settings_path.exists():
        return {}
    try:
        with open(settings_path) as f:
            settings = json.load(f)
        return settings.get("enabledPlugins", {})
    except (json.JSONDecodeError, KeyError):
        return {}


def _estimate_claude_md_tokens():
    """Estimate token count of CLAUDE.md files loaded into context."""
    total_chars = 0
    # Check CWD
    cwd_claude = Path.cwd() / "CLAUDE.md"
    if cwd_claude.exists():
        total_chars += cwd_claude.stat().st_size
    # Check parent directories (Claude Code walks up)
    for parent in Path.cwd().parents:
        pf = parent / "CLAUDE.md"
        if pf.exists():
            total_chars += pf.stat().st_size
        if parent == parent.parent:
            break
    # Check user-level
    user_claude = Path.home() / ".claude" / "CLAUDE.md"
    if user_claude.exists():
        total_chars += user_claude.stat().st_size
    # Rough: ~4 chars per token for English text
    return total_chars // 4


def _estimate_memory_tokens():
    """Estimate token count of MEMORY.md."""
    memory_path = CLAUDE_DIR / "projects"
    total = 0
    if memory_path.exists():
        for proj_dir in memory_path.iterdir():
            if proj_dir.is_dir():
                mem_file = proj_dir / "memory" / "MEMORY.md"
                if mem_file.exists():
                    total = max(total, mem_file.stat().st_size // 4)
    return total


def audit_context(events, mcp_usage):
    """Audit context overhead: MCP servers, skills, plugins, CLAUDE.md.

    Returns a dict with per-source token estimates and waste analysis.
    """
    # 1. MCP servers
    mcp_configs = _find_mcp_configs()
    servers = {}
    for source, path in mcp_configs:
        try:
            with open(path) as f:
                cfg = json.load(f)
            for name, server_cfg in cfg.get("mcpServers", {}).items():
                auto_start = server_cfg.get("autoStart", True)
                servers[name] = {
                    "source": source,
                    "auto_start": auto_start,
                    "config_path": str(path),
                }
        except (json.JSONDecodeError, KeyError):
            continue

    # 2. Estimate tool counts per server
    tools_seen_per_server = _count_mcp_tools_from_events(events)
    calls_per_server = {}
    for e in events:
        if e.get("type") != "PostToolUse":
            continue
        tool = e.get("tool", "")
        if tool.startswith("mcp__"):
            server = tool.split("__")[1]
            calls_per_server[server] = calls_per_server.get(server, 0) + 1

    mcp_audit = []
    total_mcp_tools = 0
    for name, info in servers.items():
        seen = tools_seen_per_server.get(name, 0)
        estimated_tools = _estimate_server_tools(name, seen)
        calls = calls_per_server.get(name, 0)
        tokens_per_msg = estimated_tools * CONTEXT_COSTS["deferred_tool_listing"]
        total_mcp_tools += estimated_tools
        mcp_audit.append({
            "server": name,
            "source": info["source"],
            "auto_start": info["auto_start"],
            "estimated_tools": estimated_tools,
            "tools_actually_used": seen,
            "total_calls": calls,
            "tokens_per_msg": tokens_per_msg,
            "status": "unused" if calls == 0 else "light" if calls < 10 else "active",
        })

    mcp_audit.sort(key=lambda x: (-x["tokens_per_msg"]))

    # 3. Skills & plugins
    skill_count = _count_skills()
    plugins = _count_plugins()
    # Plugins inject additional skills (estimated ~20-40 per plugin)
    plugin_skill_estimate = len(plugins) * 30
    total_skills = skill_count + plugin_skill_estimate

    # 4. CLAUDE.md and MEMORY.md
    claude_md_tokens = _estimate_claude_md_tokens()
    memory_tokens = _estimate_memory_tokens()

    # 5. Compute totals
    mcp_tool_tokens = total_mcp_tools * CONTEXT_COSTS["deferred_tool_listing"]
    mcp_instr_tokens = len(servers) * CONTEXT_COSTS["mcp_instructions"]
    skill_tokens = total_skills * CONTEXT_COSTS["skill_listing"]
    total_context = mcp_tool_tokens + mcp_instr_tokens + skill_tokens + claude_md_tokens + memory_tokens

    # 6. Compute waste (unused servers + unused skills estimate)
    unused_servers = [s for s in mcp_audit if s["status"] == "unused" and s["auto_start"]]
    unused_mcp_tokens = sum(s["tokens_per_msg"] for s in unused_servers)
    # Conservatively estimate 70% of skills are never invoked
    unused_skill_tokens = int(skill_tokens * 0.7)
    total_waste_per_msg = unused_mcp_tokens + unused_skill_tokens

    return {
        "mcp_servers": mcp_audit,
        "total_mcp_tools": total_mcp_tools,
        "skill_count": total_skills,
        "local_skills": skill_count,
        "plugin_count": len(plugins),
        "plugin_names": list(plugins.keys()),
        "claude_md_tokens": claude_md_tokens,
        "memory_tokens": memory_tokens,
        "breakdown": {
            "mcp_tool_listings": mcp_tool_tokens,
            "mcp_instructions": mcp_instr_tokens,
            "skill_listings": skill_tokens,
            "claude_md": claude_md_tokens,
            "memory_md": memory_tokens,
        },
        "total_context_per_msg": total_context,
        "waste_per_msg": total_waste_per_msg,
        "unused_servers": unused_servers,
        "unused_mcp_tokens": unused_mcp_tokens,
        "unused_skill_tokens": unused_skill_tokens,
    }


# ── Report ────────────────────────────────────────────────

SEVERITY_ICON = {"high": "[!!]", "medium": "[! ]", "low": "[  ]"}
SEVERITY_LABEL = {"high": "HIGH", "medium": "MEDIUM", "low": "LOW"}


def fmt(n):
    return f"{n:,}"


def wrap(text, prefix="     >> ", cont="        ", width=68):
    lines = []
    line = prefix
    for w in text.split():
        if len(line) + len(w) + 1 > width:
            lines.append(line)
            line = cont + w
        else:
            line += (" " + w) if line.strip() else w
    if line.strip():
        lines.append(line)
    return "\n".join(lines)


def print_context_audit(ctx):
    """Print the context overhead audit section."""
    print("\nCONTEXT OVERHEAD (tokens loaded per message)")
    print("-" * 64)

    bk = ctx["breakdown"]
    rows = [
        ("MCP tool listings", f"~{ctx['total_mcp_tools']} tools", bk["mcp_tool_listings"]),
        ("MCP server instructions", f"{len(ctx['mcp_servers'])} servers", bk["mcp_instructions"]),
        ("Skill listings", f"~{ctx['skill_count']} skills", bk["skill_listings"]),
        ("CLAUDE.md", "", bk["claude_md"]),
        ("MEMORY.md", "", bk["memory_md"]),
    ]
    for label, detail, tokens in rows:
        detail_str = f"  ({detail})" if detail else ""
        print(f"  {label:<30}{detail_str:<22} ~{fmt(tokens):>7}")
    print(f"  {'-' * 52}{'-' * 12}")
    print(f"  {'TOTAL':<52} ~{fmt(ctx['total_context_per_msg']):>7}")

    # Unused MCP servers
    if ctx["unused_servers"]:
        print(f"\n  UNUSED MCP SERVERS (0 calls, still loaded):")
        for s in ctx["unused_servers"]:
            print(f"    {s['server']:<25} ~{s['estimated_tools']} tools  "
                  f"= ~{fmt(s['tokens_per_msg'])} tokens/msg")
        print(f"    {'-' * 50}")
        print(f"    Removable MCP overhead:    ~{fmt(ctx['unused_mcp_tokens'])} tokens/msg")

    # Waste summary
    if ctx["waste_per_msg"] > 0:
        print(f"\n  ESTIMATED CONTEXT WASTE:     ~{fmt(ctx['waste_per_msg'])} tokens/msg")
        pct = round(ctx["waste_per_msg"] / ctx["total_context_per_msg"] * 100) if ctx["total_context_per_msg"] else 0
        print(f"  ({pct}% of context overhead is estimated unused)")
        print()
        if ctx["unused_servers"]:
            names = ", ".join(s["server"] for s in ctx["unused_servers"])
            print(wrap(f"Consider removing unused MCP servers: {names}. "
                       f"Each server's tool listings consume tokens in every message "
                       f"even if you never call them.", prefix="  >> ", cont="     "))
        if ctx["unused_skill_tokens"] > 500:
            print(wrap(f"~{ctx['skill_count']} skills are listed in your system prompt. "
                       f"Plugins ({', '.join(ctx['plugin_names']) or 'none'}) inject "
                       f"bundled skills -- consider disabling plugins you don't actively use.",
                       prefix="  >> ", cont="     "))


def print_report(findings, trends, tod, mcp, enhanced, period, n_events, n_sessions, context_audit=None):
    print()
    print("=" * 64)
    print("  CLAUDE CODE EFFICIENCY REPORT")
    print("=" * 64)
    print(f"  Period:      {period}")
    print(f"  Sessions:    {n_sessions}")
    print(f"  Tool calls:  {fmt(n_events)}")
    print(f"  Generated:   {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 64)

    total_waste = 0
    actionable = [f for f in findings if f["severity"] != "low"]
    low = [f for f in findings if f["severity"] == "low"]

    if actionable:
        print("\nFINDINGS")
        print("-" * 64)
        for i, f in enumerate(actionable, 1):
            waste = f.get("est_token_waste", 0)
            total_waste += waste
            print(f"\n  {i}. {SEVERITY_ICON[f['severity']]} {f['name']}  ({SEVERITY_LABEL[f['severity']]})")
            print(f"     {'~' * 50}")

            if f["id"] == "bash_overuse":
                print(f"     Bash calls: {fmt(f['bash_count'])} / {fmt(f['total_tools'])} ({f['ratio']}%)")
                print(f"     Healthy range: {f['healthy_range']}")
                if f["worst_sessions"]:
                    ws = f["worst_sessions"][0]
                    print(f"     Worst session: {ws['session']}... ({ws['bash_pct']}% Bash)")
            elif f["id"] == "search_churn":
                print(f"     Churn loops: {f['instances']}  |  Wasted calls: {fmt(f['total_churn_calls'])}")
            elif f["id"] == "toolsearch_overhead":
                print(f"     ToolSearch calls: {fmt(f['count'])} ({f['ratio_pct']}% of all tools)")
            elif f["id"] == "read_after_edit":
                print(f"     Unnecessary re-reads: {fmt(f['count'])}")
            elif f["id"] == "rapid_fire_edits":
                print(f"     Edit bursts: {f['burst_count']}  |  Extra edits: {f['extra_edits']}")
            elif f["id"] == "agent_overuse":
                print(f"     Agent calls: {f['agent_count']} ({f['ratio_pct']}%)  |  Healthy: {f['healthy_range']}")
            elif f["id"] == "websearch_for_local":
                print(f"     WebSearches: {f['total_websearches']} total, ~{f['likely_local']} likely local")

            print(f"     Est. token waste: ~{fmt(waste)}")
            print(wrap(f["recommendation"]))

    if low:
        total_waste += sum(f.get("est_token_waste", 0) for f in low)
        print(f"\n  + {len(low)} low-severity patterns (no action needed)")

    if not actionable and not low:
        print("\n  No inefficiency patterns detected. Nice work!")

    print(f"\n{'-' * 64}")
    avg = total_waste // n_sessions if n_sessions else 0
    print(f"  TOTAL ESTIMATED TOKEN WASTE:     ~{fmt(total_waste)}")
    print(f"  PER SESSION AVERAGE:             ~{fmt(avg)}")
    if avg > 5000:
        print(f"  POTENTIAL SAVINGS:               ~{round(avg / 50000 * 100)}% per session")
    print(f"{'-' * 64}")

    if len(trends) >= 2:
        print("\nWEEKLY TRENDS")
        print("-" * 64)
        print(f"  {'Week':<10} {'Sess':>5} {'Tools':>7} {'Bash%':>7} {'Agent%':>7} {'TSrch%':>7}")
        for t in trends[-6:]:
            print(f"  {t['week']:<10} {t['sessions']:>5} {t['tools']:>7} {t['bash_pct']:>6.1f}% {t['agent_pct']:>6.1f}% {t['ts_pct']:>6.1f}%")
        r, p = trends[-1], trends[-2]
        d = "improving" if r["bash_pct"] < p["bash_pct"] else "worsening" if r["bash_pct"] > p["bash_pct"] else "stable"
        print(f"\n  Bash trend: {d} ({p['bash_pct']}% -> {r['bash_pct']}%)")

    print("\nPEAK HOURS")
    print("-" * 64)
    for h in sorted(tod, key=lambda x: -x["count"])[:5]:
        print(f"  {h['hour']:02d}:00  {h['bar']:<30} {h['count']:>5} ({h['pct']}%)")

    if mcp:
        print("\nMCP TOOL USAGE")
        print("-" * 64)
        for name, count in sorted(mcp.items(), key=lambda x: -x[1]):
            print(f"  {name:<30} {count:>6} calls")

    if enhanced["has_data"]:
        print("\nERROR & DENIAL TRACKING")
        print("-" * 64)
        print(f"  Tool errors: {enhanced['errors']['total']}")
        for tool, cnt in enhanced["errors"]["by_tool"].items():
            print(f"    {tool}: {cnt}")
        print(f"  Permission denials: {enhanced['denials']['total']}")
        for tool, cnt in enhanced["denials"]["by_tool"].items():
            print(f"    {tool}: {cnt}")
    else:
        print("\n  [Enhanced hooks not yet installed -- see README for setup]")

    if context_audit:
        print_context_audit(context_audit)

    print(f"\n{'=' * 64}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Claude Code Efficiency Analyzer -- detect wasteful patterns, save tokens",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python cc_efficiency.py              # Last 7 days\n"
               "  python cc_efficiency.py --days 30    # Last 30 days\n"
               "  python cc_efficiency.py --all        # All time\n"
               "  python cc_efficiency.py --json       # JSON output\n",
    )
    parser.add_argument("--days", type=int, default=7, help="Analyze last N days (default: 7)")
    parser.add_argument("--all", action="store_true", help="Analyze all time")
    parser.add_argument("--json", action="store_true", help="Output JSON instead of formatted report")
    parser.add_argument("--context-audit", action="store_true",
                        help="Audit context overhead: MCP servers, skills, plugins loaded but unused")
    parser.add_argument("--project", type=str, default=None,
                        help="Project directory to scan for .mcp.json and CLAUDE.md (default: CWD)")
    args = parser.parse_args()

    if args.project:
        import os
        os.chdir(args.project)

    if args.all:
        since_ts = None
        period = "All time"
    else:
        since = datetime.now() - timedelta(days=args.days)
        since_ts = int(since.timestamp() * 1000)
        period = f"Last {args.days} days ({since.strftime('%b %d')} - {datetime.now().strftime('%b %d, %Y')})"

    events = load_jsonl(EVENTS_FILE, since_ts)
    if not events:
        print("No dashboard events found.")
        print(f"Expected: {EVENTS_FILE}")
        print()
        print("This file is generated by a PostToolUse hook in Claude Code.")
        print("See README.md for setup instructions.")
        sys.exit(1)

    sessions = group_by_session(events)
    n_events = sum(1 for e in events if e.get("type") == "PostToolUse")
    n_sessions = len(sessions)

    findings = sorted([
        detect_bash_overuse(sessions),
        detect_search_churn(sessions),
        detect_toolsearch_overhead(events),
        detect_read_after_edit(sessions),
        detect_rapid_fire_edits(sessions),
        detect_agent_overuse(sessions),
        detect_websearch_for_local(sessions),
    ], key=lambda f: ({"high": 0, "medium": 1, "low": 2}[f["severity"]], -f.get("est_token_waste", 0)))

    trends = compute_weekly_trends(events)
    tod = compute_time_of_day(events)
    mcp = analyze_mcp_adoption(events)
    enhanced = analyze_enhanced(EFFICIENCY_DB, since_ts)
    ctx = audit_context(events, mcp) if args.context_audit else None

    if args.json:
        result = {
            "period": period, "sessions": n_sessions, "total_tool_calls": n_events,
            "generated": datetime.now().isoformat(), "findings": findings,
            "trends": trends, "peak_hours": tod, "mcp_adoption": mcp, "enhanced": enhanced,
            "total_est_token_waste": sum(f.get("est_token_waste", 0) for f in findings),
        }
        if ctx:
            result["context_audit"] = ctx
        print(json.dumps(result, indent=2, default=str))
    else:
        print_report(findings, trends, tod, mcp, enhanced, period, n_events, n_sessions, ctx)


if __name__ == "__main__":
    main()
