#!/usr/bin/env python3
"""
cc-efficiency — Claude Code Efficiency Analyzer

Detects wasteful usage patterns in your Claude Code sessions,
estimates token overhead, and gives actionable recommendations.

Reads from ~/.claude/.dashboard-events.jsonl (generated by hooks).
Zero dependencies — Python 3.8+ stdlib only.

Usage:
    python cc_efficiency.py              # Last 7 days
    python cc_efficiency.py --days 30    # Last 30 days
    python cc_efficiency.py --all        # All time
    python cc_efficiency.py --json       # Machine-readable output
"""

import json
import sys
import argparse
from datetime import datetime, timedelta
from collections import defaultdict, Counter
from pathlib import Path

CLAUDE_DIR = Path.home() / ".claude"
EVENTS_FILE = CLAUDE_DIR / ".dashboard-events.jsonl"
HISTORY_FILE = CLAUDE_DIR / "history.jsonl"
EFFICIENCY_DB = CLAUDE_DIR / ".efficiency-events.jsonl"

# Token cost heuristics (conservative per-call estimates)
TOKEN_COSTS = {
    "bash_for_search": 400,
    "read_after_edit": 800,
    "search_churn_cycle": 1200,
    "toolsearch_call": 350,
    "agent_for_simple": 6000,
    "rapid_fire_edits": 200,
    "web_search_local": 1500,
}


def load_jsonl(path, since_ts=None):
    items = []
    if not path.exists():
        return items
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
                if since_ts and e.get("timestamp", 0) < since_ts:
                    continue
                items.append(e)
            except json.JSONDecodeError:
                continue
    return items


def group_by_session(events):
    sessions = defaultdict(list)
    for e in events:
        if e.get("type") == "PostToolUse":
            sessions[e.get("sessionId", "unknown")].append(e)
    for sid in sessions:
        sessions[sid].sort(key=lambda x: x.get("timestamp", 0))
    return dict(sessions)


# ── Detectors ─────────────────────────────────────────────

def detect_bash_overuse(sessions):
    """Bash calls that should be Grep/Read/Glob — high ratio = shell habit."""
    total_tools = bash_count = 0
    per_session = []
    for sid, events in sessions.items():
        s_total = len(events)
        s_bash = sum(1 for e in events if e.get("tool") == "Bash")
        total_tools += s_total
        bash_count += s_bash
        if s_total >= 10:
            per_session.append({"session": sid[:8], "bash_pct": round(s_bash / s_total * 100, 1),
                                "bash_count": s_bash, "total": s_total})

    ratio = bash_count / total_tools if total_tools else 0
    worst = sorted(per_session, key=lambda x: -x["bash_pct"])[:3]
    wasted = max(0, bash_count - int(total_tools * 0.15))
    return {
        "id": "bash_overuse", "name": "Bash Overuse",
        "severity": "high" if ratio > 0.25 else "medium" if ratio > 0.18 else "low",
        "bash_count": bash_count, "total_tools": total_tools,
        "ratio": round(ratio * 100, 1), "healthy_range": "10-15%",
        "worst_sessions": worst, "wasted_calls": wasted,
        "est_token_waste": wasted * TOKEN_COSTS["bash_for_search"],
        "recommendation": "Use Grep instead of grep/rg in Bash. Use Read instead of cat/head/tail. "
                          "Use Glob instead of find/ls. Dedicated tools return structured output "
                          "(fewer tokens) and skip shell overhead.",
    }


def detect_search_churn(sessions):
    """4+ consecutive Grep/Read/Glob calls — can't find what you need."""
    churn = []
    for sid, events in sessions.items():
        window = []
        for e in events:
            tool = e.get("tool", "")
            if tool in ("Grep", "Read", "Glob"):
                window.append({"tool": tool, "ts": e.get("timestamp", 0)})
            else:
                if len(window) >= 4:
                    sc = sum(1 for w in window if w["tool"] in ("Grep", "Glob"))
                    rc = sum(1 for w in window if w["tool"] == "Read")
                    if sc >= 2 and rc >= 2:
                        churn.append({"session": sid[:8], "length": len(window),
                                      "duration_s": round((window[-1]["ts"] - window[0]["ts"]) / 1000, 1)})
                window = []
        if len(window) >= 4:
            sc = sum(1 for w in window if w["tool"] in ("Grep", "Glob"))
            rc = sum(1 for w in window if w["tool"] == "Read")
            if sc >= 2 and rc >= 2:
                churn.append({"session": sid[:8], "length": len(window),
                              "duration_s": round((window[-1]["ts"] - window[0]["ts"]) / 1000, 1)})

    return {
        "id": "search_churn", "name": "Search Churn (Floundering)",
        "severity": "high" if len(churn) > 10 else "medium" if len(churn) > 3 else "low",
        "instances": len(churn), "total_churn_calls": sum(c["length"] for c in churn),
        "worst": sorted(churn, key=lambda x: -x["length"])[:5],
        "est_token_waste": len(churn) * TOKEN_COSTS["search_churn_cycle"],
        "recommendation": "When you can't find something in 2 searches, use the Explore agent "
                          "or ask Claude to search more broadly. Add glob filters to Grep. "
                          "Add key file paths to CLAUDE.md so Claude knows where to look.",
    }


def detect_toolsearch_overhead(events):
    """ToolSearch loads MCP schemas at runtime — pre-allow tools instead."""
    count = sum(1 for e in events if e.get("type") == "PostToolUse" and e.get("tool") == "ToolSearch")
    total = sum(1 for e in events if e.get("type") == "PostToolUse")
    return {
        "id": "toolsearch_overhead", "name": "ToolSearch Overhead",
        "severity": "high" if count > 100 else "medium" if count > 30 else "low",
        "count": count, "ratio_pct": round(count / total * 100, 1) if total else 0,
        "est_token_waste": count * TOKEN_COSTS["toolsearch_call"],
        "recommendation": "Add frequently-used MCP tools to permissions.allow in settings.json "
                          "so schemas load upfront. Example: 'mcp__duckdb__*' saves ~350 tokens "
                          "per avoided ToolSearch.",
    }


def detect_read_after_edit(sessions):
    """Read within 5s of Edit — unnecessary verification."""
    count = 0
    for sid, events in sessions.items():
        for i in range(1, len(events)):
            if (events[i - 1].get("tool") == "Edit" and events[i].get("tool") == "Read"
                    and events[i]["timestamp"] - events[i - 1]["timestamp"] < 5000):
                count += 1
    return {
        "id": "read_after_edit", "name": "Read-After-Edit Verification",
        "severity": "medium" if count > 20 else "low",
        "count": count, "est_token_waste": count * TOKEN_COSTS["read_after_edit"],
        "recommendation": "Edit confirms success -- no need to re-read. Add to CLAUDE.md: "
                          "'Do not re-read a file after editing to verify.'",
    }


def detect_rapid_fire_edits(sessions):
    """4+ Edit calls within 10s — should be batched into fewer calls."""
    bursts = []
    for sid, events in sessions.items():
        window = []
        for e in events:
            if e.get("tool") == "Edit":
                if window and e["timestamp"] - window[-1]["timestamp"] > 10000:
                    if len(window) >= 4:
                        bursts.append({"session": sid[:8], "count": len(window),
                                       "span_s": round((window[-1]["timestamp"] - window[0]["timestamp"]) / 1000, 1)})
                    window = []
                window.append(e)
            else:
                if len(window) >= 4:
                    bursts.append({"session": sid[:8], "count": len(window),
                                   "span_s": round((window[-1]["timestamp"] - window[0]["timestamp"]) / 1000, 1)})
                window = []
    extra = sum(max(0, b["count"] - 2) for b in bursts)
    return {
        "id": "rapid_fire_edits", "name": "Rapid-Fire Small Edits",
        "severity": "medium" if len(bursts) > 10 else "low",
        "burst_count": len(bursts), "extra_edits": extra,
        "worst": sorted(bursts, key=lambda x: -x["count"])[:5],
        "est_token_waste": extra * TOKEN_COSTS["rapid_fire_edits"],
        "recommendation": "Multiple tiny edits cost tokens per round-trip. Describe related "
                          "changes together so Claude batches them. Use Write for full rewrites "
                          "instead of many incremental edits.",
    }


def detect_agent_overuse(sessions):
    """Agent spawns for tasks solvable with 1-2 direct tool calls."""
    agent_count = total = 0
    for sid, events in sessions.items():
        for e in events:
            total += 1
            if e.get("tool") == "Agent":
                agent_count += 1
    ratio = agent_count / total if total else 0
    excess = max(0, agent_count - int(total * 0.05))
    return {
        "id": "agent_overuse", "name": "Agent Spawn Overhead",
        "severity": "high" if ratio > 0.08 else "medium" if ratio > 0.04 else "low",
        "agent_count": agent_count, "total_tools": total,
        "ratio_pct": round(ratio * 100, 1), "healthy_range": "1-3%",
        "excess": excess, "est_token_waste": excess * TOKEN_COSTS["agent_for_simple"],
        "recommendation": "Each Agent duplicates conversation context (~6K+ tokens). Use Grep/Read "
                          "directly for simple lookups. Reserve Agent for multi-step research or "
                          "parallel independent tasks.",
    }


def detect_websearch_for_local(sessions):
    """WebSearch followed by local search — answer was in the codebase."""
    total_ws = ws_then_local = 0
    for sid, events in sessions.items():
        for i, e in enumerate(events):
            if e.get("tool") == "WebSearch":
                total_ws += 1
                following = events[i + 1:i + 4]
                if sum(1 for f in following if f.get("tool") in ("Read", "Grep", "Glob")) >= 2:
                    ws_then_local += 1
    return {
        "id": "websearch_for_local", "name": "WebSearch for Local Answers",
        "severity": "medium" if ws_then_local > 5 else "low",
        "total_websearches": total_ws, "likely_local": ws_then_local,
        "est_token_waste": ws_then_local * TOKEN_COSTS["web_search_local"],
        "recommendation": "WebSearch results inject many tokens. Search locally first. Add "
                          "architecture notes to CLAUDE.md so Claude checks the codebase "
                          "before the web.",
    }


# ── Trends & Metrics ─────────────────────────────────────

def compute_weekly_trends(events):
    weeks = defaultdict(lambda: {"tool_count": 0, "bash": 0, "agent": 0, "ts": 0, "sessions": set()})
    for e in events:
        if e.get("type") != "PostToolUse":
            continue
        dt = datetime.fromtimestamp(e.get("timestamp", 0) / 1000)
        wk = dt.strftime("%Y-W%W")
        tool = e.get("tool", "")
        weeks[wk]["tool_count"] += 1
        weeks[wk]["sessions"].add(e.get("sessionId", ""))
        if tool == "Bash": weeks[wk]["bash"] += 1
        if tool == "Agent": weeks[wk]["agent"] += 1
        if tool == "ToolSearch": weeks[wk]["ts"] += 1

    trends = []
    for wk in sorted(weeks):
        w = weeks[wk]
        t = w["tool_count"]
        if t < 10:
            continue
        trends.append({"week": wk, "sessions": len(w["sessions"]), "tools": t,
                        "bash_pct": round(w["bash"] / t * 100, 1),
                        "agent_pct": round(w["agent"] / t * 100, 1),
                        "ts_pct": round(w["ts"] / t * 100, 1)})
    return trends


def compute_time_of_day(events):
    hours = Counter()
    for e in events:
        if e.get("type") == "PostToolUse":
            hours[datetime.fromtimestamp(e["timestamp"] / 1000).hour] += 1
    total = sum(hours.values()) or 1
    return [{"hour": h, "count": hours.get(h, 0), "pct": round(hours.get(h, 0) / total * 100, 1),
             "bar": "#" * int(hours.get(h, 0) / total * 100 * 2)} for h in range(24)]


def analyze_mcp_adoption(events):
    mcp = Counter()
    for e in events:
        if e.get("type") == "PostToolUse":
            tool = e.get("tool", "")
            if tool.startswith("mcp__"):
                mcp[tool.split("__")[1]] += 1
    return dict(mcp.most_common())


def analyze_enhanced(path, since_ts):
    items = load_jsonl(path, since_ts)
    errors = [e for e in items if e.get("event") == "PostToolUseFailure"]
    denials = [e for e in items if e.get("event") == "PermissionDenied"]
    return {
        "errors": {"total": len(errors), "by_tool": dict(Counter(e.get("tool", "?") for e in errors).most_common(5))},
        "denials": {"total": len(denials), "by_tool": dict(Counter(e.get("tool", "?") for e in denials).most_common(5))},
        "has_data": len(items) > 0,
    }


# ── Report ────────────────────────────────────────────────

SEVERITY_ICON = {"high": "[!!]", "medium": "[! ]", "low": "[  ]"}
SEVERITY_LABEL = {"high": "HIGH", "medium": "MEDIUM", "low": "LOW"}


def fmt(n):
    return f"{n:,}"


def wrap(text, prefix="     >> ", cont="        ", width=68):
    lines = []
    line = prefix
    for w in text.split():
        if len(line) + len(w) + 1 > width:
            lines.append(line)
            line = cont + w
        else:
            line += (" " + w) if line.strip() else w
    if line.strip():
        lines.append(line)
    return "\n".join(lines)


def print_report(findings, trends, tod, mcp, enhanced, period, n_events, n_sessions):
    print()
    print("=" * 64)
    print("  CLAUDE CODE EFFICIENCY REPORT")
    print("=" * 64)
    print(f"  Period:      {period}")
    print(f"  Sessions:    {n_sessions}")
    print(f"  Tool calls:  {fmt(n_events)}")
    print(f"  Generated:   {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 64)

    total_waste = 0
    actionable = [f for f in findings if f["severity"] != "low"]
    low = [f for f in findings if f["severity"] == "low"]

    if actionable:
        print("\nFINDINGS")
        print("-" * 64)
        for i, f in enumerate(actionable, 1):
            waste = f.get("est_token_waste", 0)
            total_waste += waste
            print(f"\n  {i}. {SEVERITY_ICON[f['severity']]} {f['name']}  ({SEVERITY_LABEL[f['severity']]})")
            print(f"     {'~' * 50}")

            if f["id"] == "bash_overuse":
                print(f"     Bash calls: {fmt(f['bash_count'])} / {fmt(f['total_tools'])} ({f['ratio']}%)")
                print(f"     Healthy range: {f['healthy_range']}")
                if f["worst_sessions"]:
                    ws = f["worst_sessions"][0]
                    print(f"     Worst session: {ws['session']}... ({ws['bash_pct']}% Bash)")
            elif f["id"] == "search_churn":
                print(f"     Churn loops: {f['instances']}  |  Wasted calls: {fmt(f['total_churn_calls'])}")
            elif f["id"] == "toolsearch_overhead":
                print(f"     ToolSearch calls: {fmt(f['count'])} ({f['ratio_pct']}% of all tools)")
            elif f["id"] == "read_after_edit":
                print(f"     Unnecessary re-reads: {fmt(f['count'])}")
            elif f["id"] == "rapid_fire_edits":
                print(f"     Edit bursts: {f['burst_count']}  |  Extra edits: {f['extra_edits']}")
            elif f["id"] == "agent_overuse":
                print(f"     Agent calls: {f['agent_count']} ({f['ratio_pct']}%)  |  Healthy: {f['healthy_range']}")
            elif f["id"] == "websearch_for_local":
                print(f"     WebSearches: {f['total_websearches']} total, ~{f['likely_local']} likely local")

            print(f"     Est. token waste: ~{fmt(waste)}")
            print(wrap(f["recommendation"]))

    if low:
        total_waste += sum(f.get("est_token_waste", 0) for f in low)
        print(f"\n  + {len(low)} low-severity patterns (no action needed)")

    if not actionable and not low:
        print("\n  No inefficiency patterns detected. Nice work!")

    print(f"\n{'-' * 64}")
    avg = total_waste // n_sessions if n_sessions else 0
    print(f"  TOTAL ESTIMATED TOKEN WASTE:     ~{fmt(total_waste)}")
    print(f"  PER SESSION AVERAGE:             ~{fmt(avg)}")
    if avg > 5000:
        print(f"  POTENTIAL SAVINGS:               ~{round(avg / 50000 * 100)}% per session")
    print(f"{'-' * 64}")

    if len(trends) >= 2:
        print("\nWEEKLY TRENDS")
        print("-" * 64)
        print(f"  {'Week':<10} {'Sess':>5} {'Tools':>7} {'Bash%':>7} {'Agent%':>7} {'TSrch%':>7}")
        for t in trends[-6:]:
            print(f"  {t['week']:<10} {t['sessions']:>5} {t['tools']:>7} {t['bash_pct']:>6.1f}% {t['agent_pct']:>6.1f}% {t['ts_pct']:>6.1f}%")
        r, p = trends[-1], trends[-2]
        d = "improving" if r["bash_pct"] < p["bash_pct"] else "worsening" if r["bash_pct"] > p["bash_pct"] else "stable"
        print(f"\n  Bash trend: {d} ({p['bash_pct']}% -> {r['bash_pct']}%)")

    print("\nPEAK HOURS")
    print("-" * 64)
    for h in sorted(tod, key=lambda x: -x["count"])[:5]:
        print(f"  {h['hour']:02d}:00  {h['bar']:<30} {h['count']:>5} ({h['pct']}%)")

    if mcp:
        print("\nMCP TOOL USAGE")
        print("-" * 64)
        for name, count in sorted(mcp.items(), key=lambda x: -x[1]):
            print(f"  {name:<30} {count:>6} calls")

    if enhanced["has_data"]:
        print("\nERROR & DENIAL TRACKING")
        print("-" * 64)
        print(f"  Tool errors: {enhanced['errors']['total']}")
        for tool, cnt in enhanced["errors"]["by_tool"].items():
            print(f"    {tool}: {cnt}")
        print(f"  Permission denials: {enhanced['denials']['total']}")
        for tool, cnt in enhanced["denials"]["by_tool"].items():
            print(f"    {tool}: {cnt}")
    else:
        print("\n  [Enhanced hooks not yet installed -- see README for setup]")

    print(f"\n{'=' * 64}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Claude Code Efficiency Analyzer -- detect wasteful patterns, save tokens",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python cc_efficiency.py              # Last 7 days\n"
               "  python cc_efficiency.py --days 30    # Last 30 days\n"
               "  python cc_efficiency.py --all        # All time\n"
               "  python cc_efficiency.py --json       # JSON output\n",
    )
    parser.add_argument("--days", type=int, default=7, help="Analyze last N days (default: 7)")
    parser.add_argument("--all", action="store_true", help="Analyze all time")
    parser.add_argument("--json", action="store_true", help="Output JSON instead of formatted report")
    args = parser.parse_args()

    if args.all:
        since_ts = None
        period = "All time"
    else:
        since = datetime.now() - timedelta(days=args.days)
        since_ts = int(since.timestamp() * 1000)
        period = f"Last {args.days} days ({since.strftime('%b %d')} - {datetime.now().strftime('%b %d, %Y')})"

    events = load_jsonl(EVENTS_FILE, since_ts)
    if not events:
        print("No dashboard events found.")
        print(f"Expected: {EVENTS_FILE}")
        print()
        print("This file is generated by a PostToolUse hook in Claude Code.")
        print("See README.md for setup instructions.")
        sys.exit(1)

    sessions = group_by_session(events)
    n_events = sum(1 for e in events if e.get("type") == "PostToolUse")
    n_sessions = len(sessions)

    findings = sorted([
        detect_bash_overuse(sessions),
        detect_search_churn(sessions),
        detect_toolsearch_overhead(events),
        detect_read_after_edit(sessions),
        detect_rapid_fire_edits(sessions),
        detect_agent_overuse(sessions),
        detect_websearch_for_local(sessions),
    ], key=lambda f: ({"high": 0, "medium": 1, "low": 2}[f["severity"]], -f.get("est_token_waste", 0)))

    trends = compute_weekly_trends(events)
    tod = compute_time_of_day(events)
    mcp = analyze_mcp_adoption(events)
    enhanced = analyze_enhanced(EFFICIENCY_DB, since_ts)

    if args.json:
        print(json.dumps({
            "period": period, "sessions": n_sessions, "total_tool_calls": n_events,
            "generated": datetime.now().isoformat(), "findings": findings,
            "trends": trends, "peak_hours": tod, "mcp_adoption": mcp, "enhanced": enhanced,
            "total_est_token_waste": sum(f.get("est_token_waste", 0) for f in findings),
        }, indent=2, default=str))
    else:
        print_report(findings, trends, tod, mcp, enhanced, period, n_events, n_sessions)


if __name__ == "__main__":
    main()
